[package]
name = "applications"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.8.1"
anyhow = "1.0.72"
network-node = { path = "../network-node" }
